version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/mongo_home:/data/db
    restart: always

  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  
  kibana:
    image: kibana:7.6.0
    ports:
      - 5601:5601
    environment:
      - discovery.type=single-node  
  
  backend:
    image: "gotasma:${BUILD_VERSION}"
    hostname: gotasma
    ports:
      - "8080:8080"
    environment:
      # HTTP
      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_HEADER_TIMEOUT=${HTTP_READ_HEADER_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_HOST=${HTTP_HOST}
      # DB
      - MONGODB_ADDRS=${MONGODB_ADDRS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_TIMEOUT=${MONGODB_TIMEOUT}
    volumes:
      - ../scripts:/scripts
    entrypoint:
      [
        "sh",
        "-c",
        "/scripts/wait-for.sh elasticsearch:9200 -q --timeout=30 -- ./gotasma.bin",
      ]
    depends_on:
      - mongodb
      - elasticsearch
      - kibana
    restart: always
