version: '3'

services:
  backend:
    image: "gotasma:${BUILD_VERSION}"
    hostname: gotasma
    ports:
      - "8080:8080"
    environment:
      # LOGGING
      - LOG_FORMAT=${LOG_FORMAT}
      # HTTP
      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_HEADER_TIMEOUT=${HTTP_READ_HEADER_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - PORT=${PORT}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_ALLOWED_ORIGINS=${HTTP_ALLOWED_ORIGINS}
      # DB
      - MONGODB_ADDRS=${MONGODB_ADDRS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_TIMEOUT=${MONGODB_TIMEOUT}
    restart: always