gen:
  success:
    code: 1000
    status: 200
    message: "Success"
  not_found:
    code: 1010
    status: 404
    message: "Not found"
  timeout:
    code: 1020
    status: 500
    message: "Timeout"
  bad_request:
    code: 1030
    status: 400
    message: "Invalid input"
  internal:
    code: 1040
    status: 500
    message: "Internal server error"
auth:
  invalid_user_password:
    code: 1200
    status: 401
    message: "Invalid email or passwrd"
user:
  duplicated_email:
    code: 1300
    status: 400
    message: "Duplicated email"
  not_found_user:
    code: 1310
    status: 400
    message: "Not found user"
holiday:
  invalid_holiday:
    code: 1450
    status: 400
    message: "Holiday must be more than 1 day"
  duplicated_holiday:
    code: 1400
    status: 400
    message: "Duplicated holiday"
  not_found_holiday:
    code: 1410
    status: 400
    message: "Not found holiday"
policy:
  unauthorized:
    code: 1100
    status: 401
    message: "You are not authorized to access this resources"
sercurity:
  invalid_action:
    code: 9999
    status: 400
    message: "You shouldn't do this!"
project:
  duplicated_project:
    code: 1500
    status: 400
    message: "Duplicated project"
  already_in_project:
    code: 1530
    status: 400
    message: "User already in project"
  not_in_project:
    code: 1520
    status: 400
    message: "User not in this project"
  not_found_project:
    code: 1510
    status: 400
    message: "Project not found"
  not_found_dev:
    code: 1540
    status: 400
    message: "Dev not found in project"